# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdrctx" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "dd4c806185556735e3a982ca01be625918c2cf93e6ab0be7ae084cdf1a43197f"
      url "https://github.com/j0urneyk/herdrctx/releases/download/v#{version}/herdrctx_#{version}_macos_x86_64.tar.gz",
        verified: "github.com/j0urneyk/herdrctx/releases/download/"
    end
    on_arm do
      sha256 "b0295b29f7b0be3e304e31b7c550819a1331fdfde62bb76f1383a50d54e0229f"
      url "https://github.com/j0urneyk/herdrctx/releases/download/v#{version}/herdrctx_#{version}_macos_aarch64.tar.gz",
        verified: "github.com/j0urneyk/herdrctx/releases/download/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c7b4491086a7f8ea7ffbe66f246d3b60e311a1e262bafdc17a4ffb6a6f53d31"
      url "https://github.com/j0urneyk/herdrctx/releases/download/v#{version}/herdrctx_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/j0urneyk/herdrctx/releases/download/"
    end
    on_arm do
      sha256 "b66ab2b38f7513d988803037b1416fa5459e4e9535316713b67137a5c397a0aa"
      url "https://github.com/j0urneyk/herdrctx/releases/download/v#{version}/herdrctx_#{version}_linux_aarch64.tar.gz",
        verified: "github.com/j0urneyk/herdrctx/releases/download/"
    end
  end

  name "herdrctx"
  desc "Terminal UI for managing local Herdr sessions"
  homepage "https://github.com/j0urneyk/herdrctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "herdrctx"

  # No zap stanza required

  caveats <<~EOS
    herdrctx requires herdr 0.6.5 or newer on your PATH.
  EOS
end
